export const productsData = [
  {
    ID: 1131,
    Name: "Nike Court Flex",
    Price: 140,
    Discount: 12,
    Category: "gripper",
    ImageSrc: "image_shoes_1.webp",
  },
  {
    ID: 1132,
    Name: "Adidas Street Pro",
    Price: 160,
    Discount: 18,
    Category: "gripper",
    ImageSrc: "image_shoes_2.webp",
  },
  {
    ID: 1133,
    Name: "Nike Run Swift",
    Price: 180,
    Discount: 15,
    Category: "run",
    ImageSrc: "image_shoes_3.png",
  },
  {
    ID: 1134,
    Name: "Nike Air Zoom",
    Price: 210,
    Discount: 22,
    Category: "run",
    ImageSrc: "image_shoes_4.png",
  },
  {
    ID: 1135,
    Name: "Nike Flex Trainer",
    Price: 195,
    Discount: 17,
    Category: "run",
    ImageSrc: "image_shoes_5.jpeg",
  },
  {
    ID: 1136,
    Name: "Nike Revolution",
    Price: 165,
    Discount: 10,
    Category: "run",
    ImageSrc: "image_shoes_6.png",
  },
  {
    ID: 1137,
    Name: "Nike Calm Slide",
    Price: 120,
    Discount: 9,
    Category: "gripper",
    ImageSrc: "image_shoes_7.jpeg",
  },
  {
    ID: 1138,
    Name: "Adidas Indoor Classic",
    Price: 155,
    Discount: 14,
    Category: "gripper",
    ImageSrc: "image_shoes_8.webp",
  },
  {
    ID: 1139,
    Name: "Nike Phantom Grip",
    Price: 230,
    Discount: 25,
    Category: "football",
    ImageSrc: "image_shoes_9.webp",
  },
  {
    ID: 1140,
    Name: "Nike Lunar Strike",
    Price: 260,
    Discount: 30,
    Category: "football",
    ImageSrc: "image_shoes_10.webp",
  },
  {
    ID: 1141,
    Name: "Nike Mercurial Pro",
    Price: 320,
    Discount: 35,
    Category: "football",
    ImageSrc: "image_shoes_11.jpeg",
  },
  {
    ID: 1142,
    Name: "Nike Speed Vapor",
    Price: 290,
    Discount: 28,
    Category: "football",
    ImageSrc: "image_shoes_12.jpeg",
  },
  {
    ID: 1143,
    Name: "Nike Zoom Edge",
    Price: 200,
    Discount: 16,
    Category: "run",
    ImageSrc: "image_shoes_13.jpeg",
  },
  {
    ID: 1144,
    Name: "Nike Street Grip X",
    Price: 175,
    Discount: 13,
    Category: "gripper",
    ImageSrc: "image_shoes_14.webp",
  },
  {
    ID: 1145,
    Name: "Adidas Predator Edge",
    Price: 340,
    Discount: 40,
    Category: "football",
    ImageSrc: "image_shoes_15.webp",
  },
  {
    ID: 1146,
    Name: "Adidas X Speedflow",
    Price: 360,
    Discount: 42,
    Category: "football",
    ImageSrc: "image_shoes_16.webp",
  },
  {
    ID: 1147,
    Name: "Adidas Predator Pro",
    Price: 380,
    Discount: 45,
    Category: "football",
    ImageSrc: "image_shoes_17.webp",
  },
  {
    ID: 1148,
    Name: "Adidas Predator Elite",
    Price: 410,
    Discount: 47,
    Category: "football",
    ImageSrc: "image_shoes_18.webp",
  },
  {
    ID: 1149,
    Name: "Nike Vapor Blue FG",
    Price: 330,
    Discount: 32,
    Category: "football",
    ImageSrc: "image_shoes_19.webp",
  },
  {
    ID: 1150,
    Name: "Nike Vapor Ice FG",
    Price: 350,
    Discount: 34,
    Category: "football",
    ImageSrc: "image_shoes_20.webp",
  },
  {
    ID: 1151,
    Name: "Nike Tiempo Legend",
    Price: 300,
    Discount: 27,
    Category: "football",
    ImageSrc: "image_shoes_21.webp",
  },
  {
    ID: 1152,
    Name: "Nike Shadow Strike",
    Price: 280,
    Discount: 24,
    Category: "football",
    ImageSrc: "image_shoes_22.webp",
  },
  {
    ID: 1153,
    Name: "Nike Speed Run Pro",
    Price: 220,
    Discount: 19,
    Category: "run",
    ImageSrc: "image_shoes_23.jpeg",
  },
  {
    ID: 1154,
    Name: "Fila Classic Run",
    Price: 150,
    Discount: 11,
    Category: "run",
    ImageSrc: "image_shoes_24.webp",
  },
  {
    ID: 1155,
    Name: "Nike Orange Sprint",
    Price: 240,
    Discount: 21,
    Category: "run",
    ImageSrc: "image_shoes_25.webp",
  },
  {
    ID: 1156,
    Name: "Nike Blue Dash",
    Price: 215,
    Discount: 18,
    Category: "run",
    ImageSrc: "image_shoes_26.webp",
  },
  {
    ID: 1157,
    Name: "Adidas Predator Dark",
    Price: 370,
    Discount: 41,
    Category: "football",
    ImageSrc: "image_shoes_27.webp",
  },
  {
    ID: 1158,
    Name: "Nike Phantom Shadow",
    Price: 345,
    Discount: 36,
    Category: "football",
    ImageSrc: "image_shoes_28.webp",
  },
  {
    ID: 1159,
    Name: "Adidas Copa Gold",
    Price: 390,
    Discount: 43,
    Category: "football",
    ImageSrc: "image_shoes_29.webp",
  },
  {
    ID: 1160,
    Name: "Nike Phantom Elite",
    Price: 420,
    Discount: 46,
    Category: "football",
    ImageSrc: "image_shoes_30.webp",
  },
  {
    ID: 1161,
    Name: "Adidas X Speed Pink",
    Price: 310,
    Discount: 29,
    Category: "football",
    ImageSrc: "image_shoes_31.webp",
  },
  {
    ID: 1162,
    Name: "Nike Vapor Rose",
    Price: 295,
    Discount: 26,
    Category: "football",
    ImageSrc: "image_shoes_32.webp",
  },
  {
    ID: 1163,
    Name: "Nike Vapor Ice White",
    Price: 325,
    Discount: 31,
    Category: "football",
    ImageSrc: "image_shoes_33.webp",
  },
  {
    ID: 1164,
    Name: "Adidas X Orange Speed",
    Price: 340,
    Discount: 33,
    Category: "football",
    ImageSrc: "image_shoes_34.webp",
  },
];
